baseURL = "https://gnglands.com"
languageCode = "en-us"
title = "GNGLANDS"

[params]

description = "Premium lands, selected carefully"
logo = "/images/logo.png"
address = "2030 W Baseline RD #182-1377 Phoenix, AZ 85041"
phone = "(480)405-5707"
email = "office@gnglands.com"



currency = "$"
areaUnit = "sq.ft."


formaction = "/"

[params.nav]
logo = "images/logo.png"
menu = [
    {name = "Home", url = "/"},
    {name = "Location", url = "#", children = [
    {name = "Arkanas", url = "/state/arkansas"},
    {name = "Arizona", url = "/state/arizona"}
  ]},
    {name = "All Properties", url = "/properties"},
    {name = "About", url = "/about"},
    {name = "Blog", url = "/blog"},
    {name = "Contact", url = "/contact"}
]

[params.social]
  whatsapp = "https://wa.me/+972546675544"
  sms = "+14804055707"
  facebook = "https://m.me/gilat.gal"
  email = "office@gnglands.com"


[taxonomies]
  state = "state"

[params.footer] #footer menu
menu = [
    {name = "Home", url = "/"},
    {name = "All Properties", url = "/properties"},
    {name = "About", url = "/about"},
    {name = "Blog", url = "/blog"},
    {name = "Contact", url = "/contact"},
    {name = "Privacy Policy", url = "/privacy-policy"},
    {name = "Refund Policy", url = "/refund-policy"}
]

menuSecondary = [
    {name = "Arkanas", url = "/state/arkansas"},
    {name = "Arizona", url = "/state/arizona"}
]
